config/routes.rb
Rails.application.routes.draw do
  get 'new', to: 'games#new'
  post 'score', to: 'games#score'
  get 'reset_score', to: 'games#reset_score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'

class GamesController < ApplicationController
  def new
    alphabet = ('A'..'Z').to_a
    @letters = []
    10.times do
      @letters << alphabet.sample
    end
  end

  def score
    # raise
    @word = params[:word].upcase
    @letters = params[:letters].split
    @output = ''
    @word.split('').uniq.each do |uniq_letter|
      word_count = @word.split('').count { |letter| letter == uniq_letter }
      grid_count = @letters.count { |letter| letter == uniq_letter }
      if word_count > grid_count
        @error = 'grid_error'
        break
      end
    end
    return unless @error.nil?

    base_url = 'https://wagon-dictionary.herokuapp.com/'
    url = "#{base_url}#{@word}"
    word_serialized = open(url).read
    word_data = JSON.parse(word_serialized)
    if word_data['found']
      @new_score = word_data['length']**2
      session[:score] = session[:score].nil? ? new_score : session[:score] + @new_score
    else
      @error = 'invalid_word'
    end
    # end
  end

  def reset_score
    session[:score] = 0
    redirect_to new_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New Game</h1>
<ul class="inline">
  <% @letters.each do |letter| %>
    <li class="tile"><%= letter %></li>
  <% end %>
</ul>
<p>What is the longest word you can find?</p>
<form action="/score" method="POST">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= hidden_field_tag :letters, @letters %>
  <input type="text" name="word" placeholder="Type a word">
  <input type="submit" name="submit" value="Play">
</form>

<p>Total score: <strong><%= session[:score] %></strong></p>

app/views/games/score.html.erb
<h1>Result</h1>
<p>
<% if @error.nil? %>
  <strong>Congratulations! </strong><%= @word %> is a valid English word!
</p><p>This word scores <strong><%= @new_score %></strong>
<% elsif @error == 'grid_error' %>
  Sorry but <strong><%= @word %></strong> can't be built out of <%= @letters.join(', ') %>
<% elsif @error == 'invalid_word' %>
  Sorry but <strong><%= @word %></strong> does not seem to be a valid English word...
<% end %>
</p>

<p>Your total score is <strong><%= session[:score] %></strong></p>

<%= link_to 'Play again', new_path %>

<br>
<br>

<%= link_to 'Reset score', reset_score_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>